#!/bin/bash

export NODE_ENV=${OVERRIDE_NODE_ENV:-$NODE_ENV}
export AWS_ACCESS_KEY_ID=${OVERRIDE_AWS_ACCESS_KEY_ID:-$AWS_ACCESS_KEY_ID}
export AWS_SECRET_ACCESS_KEY=${OVERRIDE_AWS_SECRET_ACCESS_KEY:-$AWS_SECRET_ACCESS_KEY}
export FLOW_TOKEN=${OVERRIDE_FLOW_TOKEN:-$FLOW_TOKEN}

echo "NODE_ENV is $NODE_ENV"
echo "AWS_ACCESS_KEY_ID is ${AWS_ACCESS_KEY_ID:(-4)}"
echo "AWS_SECRET_ACCESS_KEY is ${AWS_SECRET_ACCESS_KEY:(-4)}"
echo "FLOW_TOKEN is ${FLOW_TOKEN:(-4)}"
